In [5]:
import pandas as pd

In [6]:
random_par = pd.read_csv("download_paragraphs.csv", sep=",")

In [7]:
random_par = random_par.drop_duplicates()
random_par

                                                  text
0    James was leaning against the empty guard desk...
1    There was no clock on the nightstand between t...
2    Finley should’ve been happier — he should’ve b...
3    Inside a Belizean cave, you wade deeper into g...
4    Sophie had forgotten him by then. Not complete...
..                                                 ...
649  "Are you getting my texts???" she texted to hi...
650  Sometimes it's the first moment of the day tha...
651  "Explain to me again why I shouldn't cheat?" h...
652  Finding the red rose in the mailbox was a plea...
653  Betty decided to write a short story and she w...

[654 rows x 1 columns]

In [9]:
random_par['text_new'] = random_par['text'].str.split('|').str[0]
random_par

,text,text_new
0,James was leaning against the empty guard desk...,James was leaning against the empty guard desk...
1,There was no clock on the nightstand between t...,There was no clock on the nightstand between t...
2,Finley should’ve been happier — he should’ve b...,Finley should’ve been happier — he should’ve b...
3,"Inside a Belizean cave, you wade deeper into g...","Inside a Belizean cave, you wade deeper into g..."
4,Sophie had forgotten him by then. Not complete...,Sophie had forgotten him by then. Not complete...
...,...,...
649,"""Are you getting my texts???"" she texted to hi...","""Are you getting my texts???"" she texted to hi..."
650,Sometimes it's the first moment of the day tha...,Sometimes it's the first moment of the day tha...
651,"""Explain to me again why I shouldn't cheat?"" h...","""Explain to me again why I shouldn't cheat?"" h..."
652,Finding the red rose in the mailbox was a plea...,Finding the red rose in the mailbox was a plea...
653,Betty decided to write a short story and she w...,Betty decided to write a short story and she w...

In [ ]:
## add all other paragraph text preprocessing here before sending to model

In [10]:
random_par['text_new'].to_csv("tidy_paragraphs.csv", index=False)